name: ${project.artifactId}
version: ${project.version}
author: ${project.groupId}
website: ${project.url}
api-version: "1.8"
softdepend: [PlaceholderAPI]
depend: [Vault, ProtocolLib, Citizens, HolographicDisplays]
main: me.stupidbot.universalcoreremake.UniversalCoreRemake
commands:
   reloadmotd:
      aliases: motdreload
      description: Reload serverlist MOTD
      usage: /<command>
   exp:
      aliases: [xp, giveexp, givexp]
      description: Give exp
      usage: /<command> <levelup|<amount>> [player]
   setblockmeta:
      alias: setblockmetadata
      description: Set block meta
      usage: /<command> <remove|<metadata> <value>>
   readblockmeta:
      aliases: [readblockmetadata, seeblockmeta, seeblockmetadata, getblockmeta, getblockmetadata]
      description: Read block meta
      usage: /<command>
   setitemmeta:
      alias: setitemmetadata
      description: Set item meta
      usage: /<command> <remove|<metadata> <value>>
   readitemmeta:
      aliases: [readitemmetadata, seeitemmeta, seeitemmetadata, getitemmeta, getitemmetadata]
      description: Read item meta
      usage: /<command>
   emoji:
      aliases: emojis
      description: List emojis
      usage: /<command>
   openmineraltrader:
      aliases: mineraltrader
      description: Open Miner Trader GUI
      usage: /<command> [player]
   openfoodtrader:
      aliases: foodtrader
      description: Open Food Trader GUI
      usage: /<command> [player]