name: ${project.artifactId}
version: ${project.version}
author: ${project.groupId}
website: ${project.url}
api-version: 1.8
depend: [Vault, ProtocolLib, Citizens, HolographicDisplays]
main: me.stupidbot.universalcoreremake.UniversalCoreRemake
commands:
   exp:
      aliases: [xp, giveexp, givexp]
      description: Give exp
      usage: /<command> <levelup|<amount>> [player]
   setblockmeta:
      alias: setblockmetadata
      description: Set block meta
      usage: /<command> <remove|<metadata> <value>>
   emoji:
      aliases: [emojis]
      description: List emojis
      usage: /<command>
   openmineraltrader:
      aliases: [mineraltrader]
      description: Open Miner Trader GUI
      usage: /<command> [player]
   openfoodtrader:
      aliases: [foodtrader]
      description: Open Food Trader GUI
      usage: /<command> [player]
   reloadmotd:
      aliases: [motdreload]
      description: Reload serverlist MOTD
      usage: /<command>