name: ${project.artifactId}
version: ${project.version}
author: ${project.groupId}
website: ${project.url}
api-version: 1.8
depend: [Vault, ProtocolLib, Citizens, HolographicDisplays]
main: me.stupidbot.universalcoreremake.UniversalCoreRemake
commands:
   exp:
      aliases: [xp, giveexp, givexp]
      description: Give exp
      usage: /exp <levelup|<amount>> [player]
   setblockmeta:
      alias: setblockmetadata
      description: Set block meta
      usage: /setblockmeta <remove|<metadata> <value>>
   emoji:
      aliases: [emojis]
      description: List emojis
      usage: /emoji
   openmineraltrader:
      aliases: [mineraltrader]
      description: Open's Miner Trader GUI
      usage: /openmineraltrader [player]
   openfoodtrader:
      aliases: [foodtrader]
      description: Open's Food Trader GUI
      usage: /openfoodtrader [player]