name: ${project.artifactId}
version: ${project.version}
author: ${project.groupId}
website: ${project.url}
api-version: "1.8"
softdepend: [PlaceholderAPI]
depend: [Vault, ProtocolLib, Citizens, HolographicDisplays, Essentials]
main: me.stupidbot.universalcoreremake.UniversalCoreRemake
commands:
  reloadmotd:
    aliases: [motdreload, reloadserverlistmotd, serverlistmotdreload, reloadserverlist, serverlistreload]
    description: Reload serverlist MOTD
    usage: /<command>
  reloaduniversalobjectives:
    aliases: [universalobjectivesreload, questsreload, reloadquests, achievementssreload, reloadachievements, reloadobjectives, objectivesreload]
    description: Reload Universal Objectives
    usage: /<command>
  exp:
    aliases: [xp, giveexp, givexp]
    description: Give exp
    usage: /<command> <levelup|<amount>> [player]
  setblockmeta:
    aliases: [setblockmetadata]
    description: Set block meta
    usage: /<command> <remove|<metadata> <value>>
  selectobjective:
    aliases: [selectquest]
    description: Select objective
    usage: /<command> <id> [<player> [force]]
  readblockmeta:
    aliases: [readblockmetadata, seeblockmeta, seeblockmetadata, getblockmeta, getblockmetadata]
    description: Read block meta
    usage: /<command>
  setitemmeta:
    aliases: [setitemmetadata]
    description: Set item meta
    usage: /<command> <remove|<metadata> <value>>
  readitemmeta:
    aliases: [readitemmetadata, seeitemmeta, seeitemmetadata, getitemmeta, getitemmetadata]
    description: Read item meta
    usage: /<command>
  emoji:
    aliases: [emojis]
    description: List emojis
    usage: /<command>
  openmineraltrader:
    aliases: [mineraltrader]
    description: Open Miner Trader GUI
    usage: /<command> [player]
  openfoodtrader:
    aliases: [foodtrader]
    description: Open Food Trader GUI
    usage: /<command> [player]
  openstats:
    description: Open Stats GUI
    usage: /<command> [player]
  saveuniversalplayercachetofile:
    aliases: [saveuniversalplayercache, saveuniversalplayerdatatofile, saveuniversalplayerdata, saveplayerdata, saveplayercache, saveplayercachetofile, saveplayerdatatofile]
    description: Save UniversalPlayer cache to file and refresh cache
    usage: /<command>
  saveblockmetadatacachetofile:
    aliases: [saveblockmetadatacache, saveblockmetadatadatatofile, saveblockmetadatadata, saveblockmetacachetofile, saveblockmetacache, saveblockmetadatatofile, saveblockmetadata]
    description: Save block metadata cache to file
    usage: /<command>
