name: UniversalCoreRemake
version: 1.0-SNAPSHOT
author: CorruptedPrisonsDevTeam
main: me.stupidbot.universalcoreremake.UniversalCoreRemake
api-version: 1.8
website: https://github.com/StupidBot/UniversalCoreRemake
commands:
   settrail:
      aliases: [ setplayertrail, setcosmetictrail ]
      description: Set active trail
      usage: /settrail <id> [player]
   setblockmeta:
      alias: setblockmetadata
      description: Set block meta
      usage: /setblockmeta <remove|<metadata> <value>>