name: UniversalCoreRemake
version: 1.0-SNAPSHOT
author: Corrupted Prisons Dev Team
main: me.stupidbot.universalcoreremake.UniversalCoreRemake
api-version: 1.8
website: https://github.com/StupidBot/UniversalCoreRemake
commands:
   settrail:
      aliases: [ setplayertrail, setcosmetictrail ]
      description: Set active trail
      usage: /settrail <id> [player]