name: UniversalCoreRemake
version: 0.2.1
author: CorruptedPrisonsDevTeam
website: https://github.com/StupidBot/UniversalCoreRemake
api-version: "1.8"
softdepend: [PlaceholderAPI, WorldGuard, SuperVanish, PremiumVanish]
depend: [Vault, ProtocolLib, Citizens, HolographicDisplays, Essentials, Votifier]
main: me.stupidbot.universalcoreremake.UniversalCoreRemake
commands:
  reloadmotd:
    aliases: [motdreload, reloadserverlistmotd, serverlistmotdreload, reloadserverlist, serverlistreload]
    description: Reload serverlist MOTD
    usage: /<command>
  reloaduniversalobjectives:
    aliases: [universalobjectivesreload, questsreload, reloadquests, achievementssreload, reloadachievements, reloadobjectives, objectivesreload]
    description: Reload Universal Objectives
    usage: /<command>
  reloadrewards:
    aliases: [rewardsreload, reloadreward, rewardreload]
    description: Reload rewards
    usage: /<command>
  reloadminingmanager:
    aliases: [reloadmining, reloadblocks, miningreload, blocksreload, miningmanagerreload]
    description: Reload mining manager
    usage: /<command>
  reloadleaderboards:
    description: Reload leaderboards
    aliases: [leaderboardsreload, reloadleaderboard, leaderboardreload]
    usage: /<command>
  reinitializeleaderboards:
    description: Reinitialize leaderboards
    usage: /<command>
  sortleaderboards:
    aliases: [resortleaderboards, updateleaderboards]
    description: Sort leaderboards
    usage: /<command>
  exp:
    aliases: [xp, giveexp, givexp]
    description: Give exp
    usage: /<command> <levelup|<amount>> [player]
  setblockmeta:
    aliases: [setblockmetadata]
    description: Set block meta
    usage: /<command> <remove|<metadata> <value>>
  selectobjective:
    aliases: [selectquest]
    description: Select objective
    usage: /<command> <id> [<player> [force]]
  readblockmeta:
    aliases: [readblockmetadata, seeblockmeta, seeblockmetadata, getblockmeta, getblockmetadata]
    description: Read block meta
    usage: /<command>
  setitemmeta:
    aliases: [setitemmetadata]
    description: Set item meta
    usage: /<command> <remove|<metadata> <value>>
  readitemmeta:
    aliases: [readitemmetadata, seeitemmeta, seeitemmetadata, getitemmeta, getitemmetadata]
    description: Read item meta
    usage: /<command>
  resetobjective:
    description: Reset Universal Objectives
    usage: /<command> <id|all|selected|completed> [player]
  incrementobjective:
    description: Increment Universal Objectives
    usage: /<command> <id> [amt] [player]
  emoji:
    aliases: [emojis, emojilist, emojislist, emojihelp, emojishelp, emote, emotes, emotelist, emoteslist, emotehelp, emoteshelp, emoticon, emoticons, emoticonlist, emoticonslist, emoticonhelp, emoticonshelp]
    description: List emojis
    usage: /<command>
  discord:
    description: Links Discord
    usage: /<command>
  twitter:
    description: Link Twitter
    usage: /<command>
  facebook:
    aliases: [facebookpage]
    description: Link Facebook page
    usage: /<command>
  vote:
    aliases: [votelink, votelinks, votesite, vctesites, voting]
    description: List voting sites
    usage: /<command>
  openmineraltrader:
    aliases: [mineraltrader]
    description: Open Miner Trader GUI
    usage: /<command> [player]
  openfoodtrader:
    aliases: [foodtrader]
    description: Open Food Trader GUI
    usage: /<command> [player]
  openblacksmith:
    aliases: [blacksmith]
    description: Open Blacksmith GUI
    usage: /<command> [player]
  openstats:
    aliases: [stats]
    description: Open Stats GUI
    usage: /<command> [player]
  openquestmaster:
    aliases: [questmaster]
    description: Open Quest Master GUI
    usage: /<command> [player]
  openspawnportal:
    aliases: [spawnportal]
    description: Open spawn portal GUI
    usage: /<command> [player]
  openbanker:
    aliases: [banker, openbank, bank]
    description: Open spawn banker GUI
    usage: /<command> [player]
  saveuniversalplayercachetofile:
    aliases: [saveuniversalplayercache, saveuniversalplayerdatatofile, saveuniversalplayerdata, saveplayerdata, saveplayercache, saveplayercachetofile, saveplayerdatatofile]
    description: Save UniversalPlayer cache to file and refresh cache
    usage: /<command>
  saveblockmetadatacachetofile:
    aliases: [saveblockmetadatacache, saveblockmetadatadatatofile, saveblockmetadatadata, saveblockmetacachetofile, saveblockmetacache, saveblockmetadatatofile, saveblockmetadata]
    description: Save block metadata cache to file
    usage: /<command>
  saveleaderboards:
    aliases: [saveleaderboardstofile, saveleaderboardscache, saveleaderboardscachetofile]
    description: Save leaderboards data to file
    usage: /<command>
  mutate:
    aliases: [cenchant, customenchant]
    description: Add custom enchant/mutation
    usage: /<command> <enchant> [level]
  serialize:
    description: Serialize an ItemStack to a String
    usage: /<command>
  stringreward:
    description: Test a StringReward
    usage: /<command> <string_reward>
  hat:
    description: Wear an item as a hat
    usage: /<command>
  dangle:
    description: Dangle an item in front of you
    usage: /<command>
  firework:
    aliases: [fw]
    description: Launch a firework
    usage: /<command>
  fly:
    description: Toggle flight
    usage: /<command>